### ISSUE TITLE
Cannot figure out how to align middle mech with text and width

### ISSUE THREAD

**Issue by char1129** [char1129/call-to-action-banner#1]
1) Cannot figure out how to align mecha image with content tags.
Have made classes for both and made them both display elements.
2) Cannot figure out how to resize the image properly. Tried using padding which csifts the image out of alignment. Using max-width doesn't work with growth/shrinking or page properly...

Help, please.
Any tips?

I've created multiple files. Some starting from scratch and the current one this issue is posted on is a copy and edit from my hero-banner assignment.

Thank you!
@thomasjbradley @char1129

**Comment by thomasjbradley** [comment]
1. Did you figure this one out?
2. The image size: have you tried adding widths to the surrounding div tags?

**Comment by char1129** [comment]
Thank you. I did figure out the alignment. Your suggestion on thinking "outside the box" within another div to move it is helping. I am however having another issue. I'll create a new one and tag you in it.
