### ISSUE TITLE
Markbot not seeing classes

### ISSUE THREAD

**Issue by char1129** [char1129/call-to-action-banner#2]
Markbot is still expecting an element that is already added in the html. 

Please see below screen capture of Markbot's error and my html code.

Thank you!

@thomasjbradley @char1129 

<img width="794" alt="Screen Shot 2019-11-10 at 12 14 34 AM" src="https://user-images.githubusercontent.com/55107755/68539285-27028e00-034f-11ea-9eb0-513c47f44067.png">
<img width="669" alt="Screen Shot 2019-11-10 at 12 14 42 AM" src="https://user-images.githubusercontent.com/55107755/68539286-279b2480-034f-11ea-8f16-7d38487cb96d.png">

**Comment by thomasjbradley** [comment]
Where your `.body` class is, Markbot is looking for `.banner` there.

**Comment by char1129** [comment]
My brain is fried.
Thank you. That worked.
Have a good Sunday!
